
<script language="JavaScript">
  
</script>

<style>
.tmenu-mobile {
//background-color: #111;
display: none;
width: 100%;
top: 0;
z-index: 990;
}
.tmenu-mobile_positionfixed {
position: fixed;
}
//.tmenu-mobile__text {
//color: #fff;
//}
.tmenu-mobile__container {
min-height: 64px;
padding: 20px;
position: relative;
box-sizing: border-box;
display: -webkit-flex;
display: -ms-flexbox;
display: flex;
-webkit-align-items: center;
-ms-flex-align: center;
align-items: center;
-webkit-justify-content: space-between;
-ms-flex-pack: justify;
justify-content: space-between;
}
.tmenu-mobile__list {
display: block;
}
.tmenu-mobile__burgerlogo {
display: inline-block;
font-size: 24px;
font-weight: 400;
white-space: nowrap;
vertical-align: middle;
}
.tmenu-mobile__imglogo {
height: auto;
display: block;
max-width: 300px!important;
box-sizing: border-box;
padding: 0;
margin: 0 auto;
}
@media screen and (max-width: 980px) {
.tmenu-mobile__menucontent_hidden {
display: none;
height: 100%;
}
.tmenu-mobile {
display: block;
}
}
@media screen and (max-width: 980px) {
#rec206170909 .t-menuburger {
-webkit-order: 1;
-ms-flex-order: 1;
order: 1;
}
}
.t-container {
    margin-left: auto;
    margin-right: auto;
    width: 100%;
    max-width: 1200px;
    padding: 0;
}
</style>

<html>

	<head>
	<meta charset="utf-8" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

</head>
<body>

<!--metatextblock-->

   <div >
  <div class="t-cover__carrier loaded" data-content-cover-bg="https://static.tildacdn.com/tild6465-3138-4431-b437-363230323933/333.jpg" data-display-changed="true" data-content-cover-height="100vh" data-content-cover-parallax="" style="height: 100vh; background-attachment: scroll; background-image: url(&quot;https://www.opengroup.net/storage/files/pallet-1200x1200-light-0.jpg.webp&quot;);" itemscope="" itemtype="http://schema.org/ImageObject">
    <meta itemprop="image" content="https://cdn.moebelkultur.de/fileadmin/news/95c439fa420187aef313aac26090410158e639f107849fd1bf885d089eb1c409_b788864ed29bea639af2318f10669a74.jpg">

    <div style="font-size:62px;text-align:center;" data-customstyle="yes">Деревянные европоддоны Красноярск: продажа европоддонов б/у</div>

    <div class="t182__descr t-descr t-descr_lg" style="" field="descr">
      <div style="padding-top:40px;text-align:center; font-size:50px" data-customstyle="yes">200руб.шт <br>
        Оплата нал/безнал и через расчетный счет без НДС
        <br>
      </div>
        <div class="t-container" style="text-align:center; padding-top:40px"> 
  <div style="color:#2e343b; font-size: 40px;" data-customstyle="yes">КОНТАКТЫ</div>
    <div style="font-size:40px; padding-top:10px" data-customstyle="yes"><b>Тел.: 8 (953) 586 - 20 - 81</b><br> <a  href="https://wa.me/79535862081?text="Привет! Хочу купить поддоны"">WhatsApp</a><br>
      <a href="https://t.me/dmit33333i">Telegram</a> <br>E-mail: dmit33333i@yandex.ru 
<br> Доставка: бесплатно  <br> </div>
    </div>
  </div>
  </div>
</div>

</body>
</html>
